services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  
    environment:
      POSTGRES_USER: hibooxx
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: c2
  
  app:
    container_name: app_c2
    build:
      dockerfile: DockerFile
    environment:
      DATABASE_URL: postgres://hibooxx:${DB_PASSWORD}@db:5432/c2
    depends_on:
      - db
    ports:
      - "8009:8009"

volumes:
  pg_data:
